trigger:
- main

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatindSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo runnuing on $(operatingSystem)!
  displayName: 'Run a one-line script'
